version: '3.8'
services:
    postgres:
        image: postgres
        container_name: erpplus-postgres
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: 123456
            POSTGRES_DB: erpplusdb
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
    pgadmin:
        image: dpage/pgadmin4
        container_name: erpplus-pgadmin
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@admin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - "5050:80"
volumes:
    postgres-data: